# Generated by Django 4.2.5 on 2023-10-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('id_card', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('token_user', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
