# Generated by Django 4.2.5 on 2023-10-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=100)),
                ('tipo_arreglo', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('mecanico', models.CharField(max_length=100)),
                ('userfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
