# Generated by Django 4.2.5 on 2023-10-22 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='userfk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
