# Generated by Django 4.2.5 on 2023-10-22 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vehicle_userfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='userfk',
        ),
        migrations.AddField(
            model_name='usuario',
            name='userfk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
    ]
